apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: ddosapp
  name: ddosapp
  namespace: default
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: ddosapp
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: ddosapp
    spec:
      containers:
      - image: shubhashreeb09/ddos:v0
        imagePullPolicy: Always
        env:
        - name: DB_URL
          value: 192.168.86.60
        - name: DB_PORT
          value: 5342
        name: ddosapp
        resources: {}
        ports:
        - containerPort: 8080
      dnsPolicy: ClusterFirst
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: ddosapp
  name: ddosapp
  namespace: default
spec:
  ports:
  - name: http
    nodePort: 32013
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: ddosapp
  type: NodePort
